/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:1f6d8ad0-dd0d-44a3-86f2-c221baf951c7",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_bQd3Y1gbU",
    "aws_user_pools_web_client_id": "4k979ska9acmevkekr988ieom5",
    "oauth": {}
};


export default awsmobile;
